### ISSUE TITLE
Only evil can write such program to get more popularity ... - no ethic

### ISSUE THREAD

**Issue by ChameleonRed** [RonSijm/ButtFish#16]
I do not know if Niemann cheat or not so I will not do sin of blaming other. For me it is clear that there is not evidence.

Whatever what some players is doing is wrong ... whatever coding such program to get fame and propagate such evil ideas is much worse - it is like Hitler - he do not kill anybody but his people order to kill millions - he enabled killing of people.

Same wrong is with your program you enable wrong things without reason - no ethic

**Comment by ChameleonRed** [comment]
You enable not cheating for much more people what is terrible ... - you should delete this from github to stop this madness.

**Comment by RonSijm** [comment]
lmfao

**Comment by robcxyz** [comment]
Damn you got compared to Hitler with your butt project. You should leave this issue up for discussion as I think this needs a proper roasting.
