### ISSUE TITLE
Other Game Engines

### ISSUE THREAD

**Issue by TenjouUtena** [RonSijm/ButtFish#17]
Given some other things going on in high stakes game play worlds, do we need to extend ButtFish to other types of game engines?

**Comment by RonSijm** [comment]
AFAIK, Stockfish is build in compliance with [UCI](https://en.wikipedia.org/wiki/Universal_Chess_Interface) - 

So probably is you replace `stockfish_15_x64_avx2.exe` with a different engine (if you give it the same filename) - as long as the engine is compatible with UCI

**Comment by TenjouUtena** [comment]
Oh sure.   I'm talking about non-CHess engines, such as Fuego or Pachi for Go or PIO or GTO+ for Poker.   For instance.

**Comment by RonSijm** [comment]
Well for now this project is specifically for chess. It's not some "unified buttplug cheat engine" for every game. The Fish part of ButtFish refers to stockfish, a cheat engine in chess.

I can consider other games in the future though
