### ISSUE TITLE
One way communication might not be enough!

### ISSUE THREAD

**Issue by bjornkpu** [RonSijm/ButtFish#21]
### The dilemma
Some people mostly play chess in bars and pubs. In these scenarios they wouldn't always have the complete setup with cameras for image recognition or a helper that can provide ButtFish(TM) with the inputs of their opponent. Therefore this project urgently needs a way for them to communicate with the Raspberry PI with a battery-pack in a inconspicuous backpack what moves are being made.

### My proposal
A cockring-twitch-detector that encodes my ..erm.. someone's messages back to ButtFish©. Of course to not discriminate this also would include a …cave-contraction-apparatus.

### Extra features
Sometimes one can get disheartened in the quest for dominance in a particular hard game of chess. One easy fix to prevent this from happening would be that in the downtime while your opponent are thinking ButtFish® should mimic the [Rocky Theme Song](https://www.youtube.com/watch?v=r81AviZECUE).

**Comment by RonSijm** [comment]
> Some people mostly play chess in bars and pubs. 

I don't think you understand the purpose of this project... This is build for the elite of the elite, the top 0.1% of the chess world... the top #39 in the World... 

Anyways, if you want alternative ways to input the chess board state, feel free to create it, and send a pull request
