### ISSUE TITLE
How to make vibrations without needing chess moves?

### ISSUE THREAD

**Issue by mattbruv** [RonSijm/ButtFish#24]
I set up this project, and I've really been enjoying personally testing it. I was thinking it could be much better if the vibrations weren't linked to chess moves at all, but rather give an option to allow it to furiously vibrate nonstop.

**Comment by RonSijm** [comment]
Sir, my project is linking a buttplug with chess moves, and getting vibrational move feedback...

What you're describing is - just your every-other-day conventional buttplug
