### ISSUE TITLE
fallback device mechanism

### ISSUE THREAD

**Issue by mrp130** [RonSijm/ButtFish#27]
Do we need fallback mechanism in case the main device e.g. the plug is malfunction on the tournament?

**Comment by RonSijm** [comment]
A fall back mechanism such as?

**Comment by mrp130** [comment]
like applying two or more device on the recipient, when the main device malfunctioning, we can automatically or manually switch to the next registered device on queue

**Comment by RonSijm** [comment]
doesn't really seem necessary for now

If you have two devices, you can just open two instances of ButtFish, and when one fails, you start using the other
