### ISSUE TITLE
[Feature Request]: Integrate with Kafka

### ISSUE THREAD

**Issue by Erictheplague** [RonSijm/ButtFish#36]
Make a feature request to connect it to Kafka

**Comment by RonSijm** [comment]
Can you give more context about what Kafka is, and what you hope to achieve with this?

**Comment by Erictheplague** [comment]
This > https://github.com/edenhill/librdkafka

You can achieve a lot of things with this from synchronization between them etc.

**Comment by RonSijm** [comment]
Yea, I could just add serilog, since that's way more uniform that just kafka -> https://github.com/lurumad/serilog-sinks-kafka

How to do it is not really the issue here...

But I still don't know what you what you hope to achieve with this, and what the point of sending something to kafka is?

**Comment by RonSijm** [comment]
closed due to not enough info
