### ISSUE TITLE
Simplify pulses

### ISSUE THREAD

**Issue by ptlthg** [RonSijm/ButtFish#4]
Instead of using morse code which can require a lot of different pulses to transmit a position, there can be a way more simple pulse to move conversion. (Using row and column terminology for a broad audience)

My suggestion is that there be one pulse to represent adding one row or column to the position and a long vibration for 4 rows/columns.

For example, moving a piece from E5 to F4 shown in the readme can be accomplished by this sequence:
`— .` (e) `—` (4) `— . .` (f) `— .` (5)

This is because `— .` represents the E column because it's a value of 5, and E is the 5th column.
`—` represents a 4, meaning row 4 in that column.
`— . .` is a 6, which then matches to the F column, and so on.

Using `— —` for H and 8 respectively, the maximum number of pulses required to represent a move would be g6g7 or similar, which is represented by this: `— . . .` (g) `— . .` (6) `— . . .` (g) `— . . .` (7)

This effectively reduces the pulses required from 15 as it is now for e5f4 to only 8, while in the worst case 15 pulses. There is potential to simplify further, but this proposed system is easy for anyone to interpret on the fly without knowing morse code.

**Comment by RonSijm** [comment]
I've used Morse code because the original theories of how this was done was that Hans used Morse, so I used it as well. - to stay as close as possible to the actual leading theory and not invent my own method

> Instead of using morse code 
Not instead of: I was thinking of adding different _encodings_ - I can abstract the Morse encoder and let users pick a desired encoding pattern

So if I understand correct, your suggestion here is 
- I get rid of the concept of A~H, everything is 8x8
- "." represents 1
- "_" represents 4

**Comment by arrizalamin** [comment]
@WampiFlampi we can use square utilization probability from [chessbase](https://en.chessbase.com/post/study-of-square-utilization-and-occupancy) and construct a Huffman Tree, so most used squares take less than 6 bits. However, this is probably more inefficient when most engine suggestions are on the edge of the board.

**Comment by shankarsivarajan** [comment]
@arrizalamin No, that would make decoding much harder.

**Comment by RonSijm** [comment]
[Here you go.](https://github.com/RonSijm/ButtFish/commit/ba9b503233f8b69a8d811e5a932a424d7e7aa15a)

The program now supports a ICharacterEncoder that it gets from appsettings.json.
If it's missing, or anything besides "SimplifiedPulse" - it will fallback on the MorseEncoder.

Here is the ["SimplifiedPulse"](https://github.com/RonSijm/ButtFish/blob/ba9b503233f8b69a8d811e5a932a424d7e7aa15a/RonSijm.ButtFish/Encoders/SimplifiedPulseEncoder.cs) - I think it's according to your specs ;)

**Comment by ptlthg** [comment]
> The program now supports a ICharacterEncoder that it gets from appsettings.json. If it's missing, or anything besides "SimplifiedPulse" - it will fallback on the MorseEncoder.

That's great, thank you! You did understand me correctly. Having the ability to switch between them is an excellent addition.

As for other encoding suggestions here, my aim was to also make the decoding as simple as possible and I think this solves that.
